framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    session: false

    #esi: true
    #fragments: true
    php_errors:
        log: true
