version: '3'
services:
  primary:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=primary"
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
    volumes:
      - ./etc/primary.cnf:/etc/mysql/conf.d/primary.cnf
  replica:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=replica"
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
    volumes:
      - ./etc/replica.cnf:/etc/mysql/conf.d/replica.cnf
    depends_on:
      - primary
  setup:
    image: "mysql:5.7"
    environment:
      - "PRIMARY_PASSWORD=primary"
      - "REPLICA_PASSWORD=replica"
    volumes:
      - ./bin/setup-replication.sh:/setup-replication.sh
    depends_on:
      - primary
      - replica
    command: /setup-replication.sh
  app:
    build: .
    depends_on:
      - setup
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    entrypoint: /app/bin/entrypoint.sh
