version: '3'
services:
  primary:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=primary"
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
  replica:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=replica"
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
    depends_on:
      - primary
  app:
    build: .
    depends_on:
      - primary
      - replica
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
